version: '3.8'

services:

  db:
    image: postgres:15-alpine
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  back:
    depends_on:
      - db
    build: 
      context: ./back
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app
      - node_modules_back:/app/node_modules

  front:
    depends_on:
      - back
    build: 
      context: ./front
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "5173:5173"
      - "4173:4173"
    volumes:
      - ./front:/app
      - node_modules_front:/app/node_modules

volumes:
  db_data:
  node_modules_back:
  node_modules_front: