services:
  redis:
    image: redis:latest
    ports:
      - "6009:6379"
    volumes:
      - redis_data:/data

    restart: always

  db:
    image: postgres:16.1
    env_file: ./back/.env
    ports:
      - "5009:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  back:
    depends_on:
      - db
      - redis
    build:
      context: ./back
      dockerfile: Dockerfile
    env_file: ./back/.env
    ports:
      - '3009:3000'
    restart: on-failure

  front:
    depends_on:
      - back
    build:
      context: ./front
      dockerfile: Dockerfile
    env_file: ./front/.env
    ports:
      - '4009:4173'

volumes:
  db_data:
  redis_data:
