export const ERROR_CODES = {
	// --- Domaine / métier ---
	EMAIL_ALREADY_TAKEN: "EMAIL_ALREADY_TAKEN",
	USERNAME_ALREADY_TAKEN: "USERNAME_ALREADY_TAKEN",
	WORD_IN_PASSWORD: "WORD_IN_PASSWORD",
	INVALID_PASSWORD: "INVALID_PASSWORD",
	PROFILE_PICTURE_REQUIRED: "PROFILE_PICTURE_REQUIRED",
	LOCATION_REQUIRED: "LOCATION_REQUIRED",
	LOCATION_NOT_FOUND: "LOCATION_NOT_FOUND",
	LOCATION_SERVICE_UNAVAILABLE: "LOCATION_SERVICE_UNAVAILABLE",
	ORIENTATION_LOCKED_FOR_UNDEFINED_GENDER:
		"ORIENTATION_LOCKED_FOR_UNDEFINED_GENDER",
	INVALID_PICTURE_URL: "INVALID_PICTURE_URL",
	INVALID_PICTURE_URL_2: "INVALID_PICTURE_URL_2",
	DEMO_READ_ONLY: "DEMO_READ_ONLY",

	// --- WebSocket ---
	INVALID_SOCKET_MESSAGE: "INVALID_SOCKET_MESSAGE",
	INVALID_SOCKET_MESSAGE_TYPE: "INVALID_SOCKET_MESSAGE_TYPE",

	// --- Génériques / fallback ---
	UNKNOWN_ERROR: "UNKNOWN_ERROR",

	// --- Défauts HTTP (statuts sans code métier) ---
	BAD_REQUEST: "BAD_REQUEST",
	UNAUTHORIZED: "UNAUTHORIZED",
	FORBIDDEN: "FORBIDDEN",
	NOT_FOUND: "NOT_FOUND",
	PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
	INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
	BAD_GATEWAY: "BAD_GATEWAY",
	TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
