export * from "./createMessagesTableMutation"
export * from "./createUuidExtensionMutation"
export * from "./createUserTagsTableMutation"
export * from "./createUsersTableMutation"
export * from "./createPicturesTableMutation"
export * from "./createTagsTableMutation"
export * from "./createChatsTableMutation"
export * from "./dropDatabaseMutation"
export * from "./createGenderEnumMutation"
export * from "./createSexualOrientationEnumMutation"
export * from "./createVotesTableMutation"
export * from "./createViewsTableMutation"
export * from "./createReportsTableMutation"
export * from "./createUserBlocksTableMutation"
export * from "./createNotificationsTableMutation"

export * from "./createUserMutation"
